[package]
name = "gf"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = "0.29.0"
clap = { version = "4.2", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
confy = "0.5"
chrono = "0.4"